import { Injectable } from '@angular/core';
import { ZoneTourist } from './zone-tourist/zone-tourist';

@Injectable({
  providedIn: 'root'
})
export class ZoneTouristService {
   protected villeList:ZoneTourist[]=[
    {
     id:1,
     image:"assets/segou.webp",
     nom:"zone touristique de segou",
     pays:"Mali",
     ville:"Segou",
     descriptionPetit:"ville tourisque important du Mali",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/segou1.jpg",
     img2:"assets/segou2.jpg",
     img3:"assets/segou3.jpg",
     img4:"assets/imgDogon4.jpg",
     img5:"assets/imgSegou1.jpg",
     img6:"assets/imgSegou2.jpg",
     img7:"assets/imgSiby1.jpg",
     img8:"assets/imgSiby2.jpg",
     img9:"assets/segou.jpg",
     img10:"assets/imgTombouctou3.jpg"
    },
    {
     id:2,
     image:"assets/sanga.jpg",
     nom:"zone touristique du pays dogon",
     pays:"Mali",
     ville:"Pays dogon",
     descriptionPetit:"ville tourisque important du Mali situe dqns le pqys dogon",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/imgDogon1.jpg",
     img2:"assets/imgDogon2.jpg",
     img3:"assets/imgDongon3.jpg",
     img4:"assets/imgDogon4.jpg",
     img5:"assets/paysdogon5.jpg",
     img6:"assets/paysdogon1.jpg",
     img7:"assets/paysdogon2.jpg",
     img8:"assets/paysdogon3.jpg",
     img9:"assets/paysdogon4.jpg",
     img10:"assets/paysdogon6.jpg"
    },
    {
     id:3,
     image:"assets/Koulikoro.jpg",
     nom:"zone tourist de Koulikoro",
     pays:"Mali",
     ville:"Koulikoro",
     descriptionPetit:"ville tourisque important du Mali dans la region de koulikoro",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/kouli1.jpg",
     img2:"assets/kouli2.jpg",
     img3:"assets/kouli3.jpg",
     img4:"assets/kouli4.jpg",
     img5:"assets/kouli5.jpg",
     img6:"assets/kouli5.jpg",
     img7:"assets/imgSiby1.jpg",
     img8:"assets/kouli8.jpg",
     img9:"assets/imgSiby2.jpg",
     img10:"assets/kouli7.jpg"
    },
    {
     id:4,
     image:"assets/mosque.jpg",
     nom:"zone tourist de Tombouctou",
     pays:"Mali",
     ville:"Tombouctou",
     descriptionPetit:"ville tourisque important du Mali dans la region de Tombouctou",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/gao1.jpg",
     img2:"assets/gao4.jpg",
     img3:"assets/gao5.jpg",
     img4:"assets/kidal7.jpg",
     img5:"assets/kidal8.jpg",
     img6:"assets/tombouctouM.jpg",
     img7:"assets/Tombouctou.jpg",
     img8:"assets/imgTombouctou2.jpg",
     img9:"assets/imgTombouctou2.jpg",
     img10:"assets/imgTombouctou3.jpg"
    },
    {
     id:5,
     image:"assets/Djene.jpg",
     nom:"zone tourist de Djenée",
     pays:"Mali",
     ville:"Djenée",
     descriptionPetit:"ville tourisque important du Mali dans la region de San",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/imgDogon1.jpg",
     img2:"assets/imgDogon2.jpg",
     img3:"assets/imgDongon3.jpg",
     img4:"assets/imgDogon4.jpg",
     img5:"assets/imgSegou1.jpg",
     img6:"assets/imgSegou2.jpg",
     img7:"assets/imgSiby1.jpg",
     img8:"assets/imgSiby2.jpg",
     img9:"assets/imgTombouctou1.jpg",
     img10:"assets/imgTombouctou3.jpg"
    },
    {
     id:6,
     image:"assets/badiangara.jpg",
     nom:"zone touristique de Bandiangara",
     pays:"Mali",
     ville:"Badiangara",
     descriptionPetit:"ville tourisque important du Mali dans la region de Badiangara",
     descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
     img1:"assets/imgDogon1.jpg",
     img2:"assets/imgDogon2.jpg",
     img3:"assets/imgDongon3.jpg",
     img4:"assets/imgDogon4.jpg",
     img5:"assets/paysdogon1.jpg",
     img6:"assets/paysdogon2.jpg",
     img7:"assets/paysdogon3.jpg",
     img8:"assets/paysdogon4.jpg",
     img9:"assets/paysdogon5.jpg",
     img10:"assets/paysdogon6.jpg"
    },
    {
      id:7,
      image:"assets/segou1.jpg",
      nom:"zone touristique de segou",
      pays:"Mali",
      ville:"Segou",
      descriptionPetit:"ville tourisque important du Mali dans la region de koulikoro",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/segou1",
      img2:"assets/segou2.jpg",
      img3:"assets/segou3.jpg",
      img4:"assets/segou3.jpg",
      img5:"assets/imgSegou1.jpg",
      img6:"assets/imgSegou2.jpg",
      img7:"assets/imgSiby1.jpg",
      img8:"assets/imgSiby2.jpg",
      img9:"assets/segou.jpg",
      img10:"assets/segou2.jpg"
     },
     {
      id:8,
      image:"assets/mopti.jpg",
      nom:"zone tourist de Mopti",
      pays:"Mali",
      ville:"Mopti",
      descriptionPetit:"ville tourisque important du Mali dans la region de Tombouctou",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/imgDogon1.jpg",
      img2:"assets/imgDogon2.jpg",
      img3:"assets/mopti8.jpg",
      img4:"assets/mopti2.jpg",
      img5:"assets/mopti3.jpg",
      img6:"assets/mopti4.jpg",
      img7:"assets/mopti5.jpg",
      img8:"assets/mopti6.jpg",
      img9:"assets/mopti7.jpg",
      img10:"assets/mopti9.jpg"
     },
     {
      id:9,
      image:"assets/sikasso1.jpg",
      nom:"zone tourist de Sikasso",
      pays:"Mali",
      ville:"Sikasso",
      descriptionPetit:"ville tourisque important du Mali dans la region de Sikasso",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/sikasso1.jpg",
      img2:"assets/sikasso2.jpg",
      img3:"assets/sikasso3.jpg",
      img4:"assets/sikasso4.jpg",
      img5:"assets/sikasso5.jpg",
      img6:"assets/sikasso6.jpg",
      img7:"assets/imgSiby1.jpg",
      img8:"assets/imgSiby2.jpg",
      img9:"assets/sikasso7.jpg",
      img10:"assets/sikasso8.jpg"
     },
     {
      id:10,
      image:"assets/gao3.jpg",
      nom:"zone touristique de Gao au nord du Mali",
      pays:"Mali",
      ville:"Gao",
      descriptionPetit:"ville tourisque important du Mali dans la region de Badiangara",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/gao1.jpg",
      img2:"assets/gao2.jpg",
      img3:"assets/gao3.jpg",
      img4:"assets/gao4.jpg",
      img5:"assets/gao5.jpg",
      img6:"assets/kidal6.jpg",
      img7:"assets/imgSiby1.jpg",
      img8:"assets/imgSiby2.jpg",
      img9:"assets/gao5.jpg",
      img10:"assets/imgTombouctou3.jpg"
     },
     {
      id:11,
      image:"assets/badiangara.jpg",
      nom:"zone tourist au pays Dogon",
      pays:"Mali",
      ville:"Badiangara",
      descriptionPetit:"ville tourisque important du Mali dans la region de Badiangara",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/imgDogon1.jpg",
      img2:"assets/imgDogon2.jpg",
      img3:"assets/imgDongon3.jpg",
      img4:"assets/imgDogon4.jpg",
      img5:"assets/imgSegou1.jpg",
      img6:"assets/imgSegou2.jpg",
      img7:"assets/imgSiby1.jpg",
      img8:"assets/imgSiby2.jpg",
      img9:"assets/imgTombouctou1.jpg",
      img10:"assets/imgTombouctou3.jpg"
     },
     {
      id:12,
      image:"assets/badiangara.jpg",
      nom:"zone tourist au pays Dogon",
      pays:"Mali",
      ville:"Badiangara",
      descriptionPetit:"ville tourisque important du Mali dans la region de Badiangara",
      descriptionLong:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate minima possimus quam. Alias odit aut dolorum voluptatibus unde maxime modi doloribus deserunt sunt, laborum totam saepe fugiat iste quo perspiciatis!",
      img1:"assets/imgDogon1.jpg",
      img2:"assets/imgDogon2.jpg",
      img3:"assets/imgDongon3.jpg",
      img4:"assets/imgDogon4.jpg",
      img5:"assets/imgSegou1.jpg",
      img6:"assets/imgSegou2.jpg",
      img7:"assets/imgSiby1.jpg",
      img8:"assets/imgSiby2.jpg",
      img9:"assets/imgTombouctou1.jpg",
      img10:"assets/imgTombouctou3.jpg"
     }
     
 ];

  constructor() { }
  getAllZoneTouristList():ZoneTourist[]{
    return this.villeList;
  }
  getZoneTOuristById(id:number):ZoneTourist|undefined{
    return this.villeList.find(villeList=>villeList.id===id);

  }
}
